# Generated by fusen: do not edit by hand

test_that("use_jqueryi18next works", {
  tpd <- tempdir()
  oldwd <- setwd(tpd)
  unlink(file.path(tpd, "i18test"), TRUE, TRUE)
  res <- golem::create_golem(file.path(tpd, "i18test"), open = FALSE)
  setwd(file.path(tpd, "i18test"))
  use_jqueryi18next(with_test = FALSE)
    expect_true(
      file.exists("inst/app/www/i18next.min.js")
    )
    expect_true(
      file.exists("inst/app/www/jquery-i18next.min.js")
    )
    expect_true(
      file.exists("inst/app/www/i18n_locales.json")
    )
    expect_true(
      file.exists("inst/app/www/i18n_shiny.js")
    )
    expect_true(
      file.exists("inst/app/www/i18n_handlers.js")
    )
    expect_true(
      file.exists("R/fct_i18n.R")
    )
  setwd(oldwd)
})
