# Generated by fusen: do not edit by hand

test_that("use_jqueryi18next works", {
  tpd <- tempdir()
  oldwd <- setwd(tpd)
  res <- golem::create_golem("i18test")
  use_jqueryi18next(".")
  expect_true(
    file.exists("inst/app/www/i18next.min.js")
  )
  expect_true(
    file.exists("inst/app/www/jquery-i18next.min.js")
  )
  expect_true(
    file.exists("inst/app/www/locales.json")
  )
  expect_true(
    file.exists("inst/app/www/shiny-i18n.js")
  )
  expect_true(
    file.exists("R/fct_with_i18n.R")
  )
  expect_true(
    file.exists("tests/testthat/test-fct_with_i18n.R")
  )
})
